name: sellerspot database models npm package

on:
    workflow_dispatch: # for Run workflow button
        inputs:
            publishType:
                description: 'Publish Type'
                required: true
                default: 'patch'
    push:
        branches:

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/

            - name: Build
              run: npm install

            - name: echo
              run: echo ${{ github.repository }}

            - name: Version
              if: github.ref == 'refs/heads/master'
              run: npm version patch -m "Patch Version"

            - name: Publish Package
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

            - name: Tag version
              run: git push https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git --tags
