name: sellerspot database models npm package

on:
    workflow_dispatch: # for Run workflow button
        inputs:
            publishType:
                description: 'Publish Type'
                required: true
                default: 'patch'
    push:
        branches:
            - master

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/

            - name: create git directory if not existes
              continue-on-error: true
              run: mkdir ~/.git

            - name: Setting Up Identity
              continue-on-error: true
              run: git config user.email "grthayalan18@gmail.com" & git config user.name "ThayalanGR"

            - name: Build
              run: npm install

            - name: Version
              run: npm version patch -m "Patch Version"

            - name: Publish Package
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

            - name: Tag Version and Push Tags
              run: git push https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git --tags
